apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-sample-app
  name: go-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sample-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-sample-app
    spec:
      containers:
      - image: andreasevers/go-sample-app:1.0.1
        name: go-sample-app
        resources: {}
status: {}
